### ISSUE TITLE
Seems not to be compatible with actual mqtt in homie4

### ISSUE THREAD

**Issue by foehlmann** [strandborg/AlsavoCtrl#25]
**Created from Dockerfile on arm64 ->**

AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "/app/alsavo.py", line 164, in <module>
    main()
  File "/app/alsavo.py", line 156, in main
    ctrl = Device_Alsavo(f"{device_id}", f"{device_name}", mqtt_settings=mqtt_settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/alsavo.py", line 44, in __init__
    super().__init__(device_id, name, homie_settings, mqtt_settings)
  File "/usr/local/lib/python3.11/site-packages/homie/device_base.py", line 96, in __init__
    self.mqtt_client = connect_mqtt_client(self, mqtt_settings)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/homie/mqtt/homie_mqtt_client.py", line 65, in connect_mqtt_client
    mqtt_client.connect()
  File "/usr/local/lib/python3.11/site-packages/homie/mqtt/paho_mqtt_client.py", line 51, in connect
    self.mqtt_client = mqtt_client.Client(
                       ^^^^^^^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'

**Comment by strandborg** [comment]
Looks like paho-mqtt (a dependency of Homie4) was updated to version 2.0 while Homie4 is still using the earlier version. I have fixed the same issue in another project of mine, and copypasted the fix here as well: the main branch at 9ea7722ad1d19b997e52b7fe23b9a2814da0a07a should now contain a fix for this , hopefully; I have not tested this myself at all, please let me know if this fixes the issue for you.
